services:
    # Base de datos vectorial Qdrant
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        restart: always

    # Aplicación Node.js
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - qdrant
        environment:
            - NODE_ENV=production
            - QDRANT_URL=http://qdrant:6333
            - PORT=3000
            - TRANSFORMERS_CACHE=/app/.cache
        volumes:
            - ./uploads:/app/uploads
            - huggingface_cache:/app/.cache
        restart: always

volumes:
    qdrant_data:
    huggingface_cache:
